theme: minima
title: El blog de Javier36
author: Javier36´s
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  El blog de noticias numero uno de latino america se presenta en forma de fichas.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
